name: raddyn
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  # Standard data analysis libraries
  - pandas==1.*
  - scikit-learn==1.*
  - scikit-image==0.20.*
  - matplotlib==3.*

  # Standard presentation and organization tools
  - jupyterlab
  - tqdm

  # Libraries not available via Anaconda
  - pip
  - pip:
    - jupyterlab-spellchecker
    - trackpy
    - papermill
    - git+https://github.com/ivem-argonne/real-time-defect-analysis.git
